### ISSUE TITLE
Determine current touching object by distance to nearest origin rather than last touched

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK#1618]
The interact touch script at the moment determines the most current touching object based on the last object that was touched.

It would be good to have an option on the interact touch script to determine the current touching object based on which object is closest to a certain point on the interact touch script (e.g. the origin or a custom transform which could be set to the grab attach point).

This pull request already attempted to implement this feature but it is way out of date.

https://github.com/thestonefox/VRTK/pull/315

**Comment by RunenGamer** [comment]
I would like to look into this. 
I will check out the pull (#315) and will integrate it into the current feature branch (3.3.0-alpha).

 Can this pull request be labled as "w_inprogress"?

**Comment by RunenGamer** [comment]
Ok, I think it's done. 
Now, I will make a pull request.

**Comment by thestonefox** [comment]
@RunenGamer as this is a new feature, it won't be brought into 3.3.0 as i'm trying to get it tied up to be released, so after the windows mixed reality support is done then 3.3.0 should be done.

After 3.3.0 is released, then PRs are viable to be merged again but will need community support to test them and approve they work.

**Comment by thestonefox** [comment]
This is in V4 as standard
