### ISSUE TITLE
[feature] Support the headset touchpad controller of gear vr.

### ISSUE THREAD

**Issue by BensonZheng2016** [ExtendRealityLtd/VRTK#1689]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (Github 3.3.0-alpha 83c654ac72e64a02eea8d0fa07a30f72f4eb47da)
 * Version of Unity3D (Unity 2017.1.0f3)
 * Hardware used (Oculus Gear)
 * SDK used (Oculus Utilities)

### Expected behavior
I want to support the touchpad of headset.

**Comment by thestonefox** [comment]
Should just work in V4
