### ISSUE TITLE
feat:Two-handed Climbing

### ISSUE THREAD

**Issue by zmyers1** [ExtendRealityLtd/VRTK#1699]
Mentioned briefly in #397 
The current functionality for climbing allows the player to swap between controllers and grabbable objects, with only one controller influencing the play area at any given time. This feature would add a toggleable two-handed mode for the climbing script that allows both controllers to maintain a grab and influence the play area simultaneously.

While this feature isn't particularly useful when compared to the default functionality, it does provide a framework for other developers to add their own features on top, such as multihanded jumping/launching, stamina, etc.

I've considered two options:

1. Allow the secondary controller to perform a grab that does not influence the play area, but will assume control of the play area once the primary has been released.
2. Allow both controllers to maintain a fully featured grab, both influencing the play area until one or the other is released.

I have partial implementations of both for my own testing, with the second simply taking the average positions of the controllers to determine how the play area is influenced.
Key Problems I've run into:

- How to handle object rotation when both controllers grab separate objects
My current implementation only allows object rotation if only one controller is grabbing. I'm not 100% sure how to implement this with multiple objects influencing rotation.
- How to handle player controller movement when multi-grabbing
If both controllers influence the place space, the player must keep their controllers in the same relative positions in order for the on-screen controllers to remain lined up with their grabbable objects. When the player moves their controller, it's possible for them to break contact with what they were grabbing.
Maybe add a joint that breaks when the controller moves too far? Or check colliders to see if the controller is still touching the object anywhere?
- How to handle same-object climbing
At the moment the default swap-controller functionality happens in this scenario. I assume this feature would need a new secondary grab script to allow grabbing the same object with both hands.

Any thoughts or ideas?
I've never really contributed to an open source project, so let me know if I can standardize the issue or anything like that.

**Comment by thestonefox** [comment]
in V4 climbing always works on both hands
