### ISSUE TITLE
feat: VR Glove Support

### ISSUE THREAD

**Issue by DigitalSketch** [ExtendRealityLtd/VRTK#1772]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Precheck
I've  done a search for "gloves" for open and closed tickets, but didn't see a feature request.

### Environment
Unity Asset Store

### Steps to reproduce
N/A

### Expected behavior
Have gloves that do finger tracking, such as CaptoGlove, be able to interact with objects.

**Comment by thestonefox** [comment]
Would just require wrapping any 3rd party SDK around V4
