### ISSUE TITLE
Headset view is black when starting the scene using Oculus Rift

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK#1972]
### Environment

* Source of VRTK: Github
* Version of VRTK: V4 beta
* Version of the Unity software: 2018.3.11f1
* Hardware used: Oculus Rift
* SDK used: Unity.XR

### Steps to reproduce

Add a UnityXRCameraRig to the scene.

Ensure Shared Depth Buffer on the Oculus SDK is enabled

![image](https://user-images.githubusercontent.com/1029673/55385696-9dbbeb00-5525-11e9-9af4-523dec459d29.png)

Run the scene

### Expected behavior

Expect to see the scene

### Current behavior

On occasion the screen is just black.

**Comment by thestonefox** [comment]
### Workaround

Disable the Shared Depth Buffer on the Oculus SDK in Unity

This seems to be a bug in Unity and has been reported here:

https://fogbugz.unity3d.com/default.asp?1142620_hlivr9g51m9gkp9d

**Comment by jackpr-unity** [comment]
Huh, that's no good. I've scooted the fogbugz issue forward through our process a bit.

**Comment by thestonefox** [comment]
Not a VRTK bug
