### ISSUE TITLE
Install docs - mention simpler options

### ISSUE THREAD

**Issue by andybak** [ExtendRealityLtd/VRTK#1978]
For non-coders I usually recommend Git Desktop over the command line and it actually handles submodules (and LFS) fairly seamlessly.

Considering VRTK targets learners and - to some degree - non-coders would it be worth mentioning this as an option in the install docs?

**Comment by andybak** [comment]
On a related note - I just did an experiment to see how easy it was to add UPM compatibility to VRTK and the answer was "very simple": https://github.com/IxxyXR/VRTK/blob/master/package.json

With a package.json added to the main repo install instructions become as simple as: "Open Packages/manifest.json in a text editor and add the following entry"

Unity handles the git clone and submodule stuff automatically.

(I believe updating is as simple as deleting the lock entry in the same file but there's plans to add UI support for this too)

**Comment by thestonefox** [comment]
Git isn't the recommended way for users (especially beginners) to get VRTK. During beta we will implement UPM deployment (so you can get it via the Unity Package Manager) and on V4 release it will be on the Unity Asset Store.

The direct access to the repository is really only for those who want to sub module VRTK into their own project.

**Comment by andybak** [comment]
Cool. If you're planning UPM support anyway then that's better than messing with Git Desktop.

Hopefully the Asset Store will begin supporting UPM packages too eventually so everyone can benefit from not having 3rd party code strewn across their project.
