### ISSUE TITLE
Swith Scene ,Vrtk 4.0 have a  "MissingReferenceException" Warntip

### ISSUE THREAD

**Issue by 18210328369** [ExtendRealityLtd/VRTK#1979]
### Environment
* Source of VRTK : GitHub
* Version of VRTK:v4.0
* Version of the Unity software:2018.3.11
* Hardware used:Vive
* SDK used:OpenVR
### Steps to reproduce
1.creat a empty,add a unity_button_action ,to Switch scene
2.ues"SceneManager.LoadScene(xxx);"
### Expected behavior
Switch in  xxx  scene

### Current behavior
Switch in  xxx  scene
but with a warning:
MissingReferenceException: The object of type 'BooleanAction' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Zinnia.Extension.BehaviourExtensions+<>c__DisplayClass0_0.<RunWhenActiveAndEnabled>g__OnBeforeRender|0 () (at Assets/VRTK/Dependencies/Zinnia.Unity/Runtime/Extension/BehaviourExtensions.cs:20)
UnityEngine.BeforeRenderHelper.Invoke () (at C:/buildslave/unity/build/Runtime/Export/BeforeRenderHelper.cs:105)
UnityEngine.Application.InvokeOnBeforeRender () (at C:/buildslave/unity/build/Runtime/Export/Application.cs:324)

**Comment by thestonefox** [comment]
This doesn't follow the issue template. Please resubmit following the issue template so the bug can be easily re-created.

**Comment by thestonefox** [comment]
should be fixed with this PR https://github.com/ExtendRealityLtd/VRTK/pull/1976
