### ISSUE TITLE
How do I install VRTK v4?

### ISSUE THREAD

**Issue by Tageolsson** [ExtendRealityLtd/VRTK#1980]
Hi! I don't understand how to install the new v4 beta of VRTK, I don't quite get the "getting started" tutorial on your Github main page.
Earlier versions was just a matter of copying an assetfolder and some project settings, but I guess it's another process now? 

Thanks!

**Comment by thestonefox** [comment]
Github issues are for feature requests and bug reports. If you require help then join the VRTK slack channel http://invite.vrtk.io
