### ISSUE TITLE
SteamVR Version?

### ISSUE THREAD

**Issue by superjayman** [ExtendRealityLtd/VRTK#1985]
Which SteamVR version does VRTK4 support? does it work without it? Is it compatible with Oculus SDK?

**Comment by bddckr** [comment]
Version 4 of VRTK supports anything (that works in Unity). We will be offering SDK-specific tutorials as educational material at [the Academy](http://academy.vrtk.io) once we have done them.

As we're using this Issues page as a bug tracker/feature request/public roadmap tool I will close this issue and am asking you to move to our community: [Join us on Slack!](http://invite.vrtk.io)
