### ISSUE TITLE
Basic VRTK setup has ObservableListEditor.cs errors

### ISSUE THREAD

**Issue by dantman** [ExtendRealityLtd/VRTK#1986]
### Environment

* Source of VRTK: GitHub
* Version of VRTK:  841eb0e
* Version of the Unity software: 2018.3.0f2
* Hardware used: Vive
* SDK used: OpenVR

### Steps to reproduce

Follow the [Getting Started](https://github.com/ExtendRealityLtd/VRTK#getting-started) documentation and open the project in Unity.

### Expected behavior

There should be no errors in the console.

### Current behavior

The console shows the following errors. They all start with `Assets\VRTK\Dependencies\Zinnia.Unity\Editor\Data\Collection\ObservableListEditor.cs` so I've trimmed that out to make it easier to read.

```
...(9,19): error CS0234: The type or namespace name 'FodyRunner' does not exist in the namespace 'Malimbe' (are you missing an assembly reference?)
...(17,41): error CS0246: The type or namespace name 'InspectorEditor' could not be found (are you missing a using directive or an assembly reference?)
...(46,33): error CS0115: 'ObservableListEditor.DrawProperty(SerializedProperty)': no suitable method found to override
...(114,33): error CS0115: 'ObservableListEditor.ApplyModifiedProperty(SerializedProperty, bool)': no suitable method found to override
...(125,33): error CS0115: 'ObservableListEditor.BeforeChange(SerializedProperty)': no suitable method found to override
...(160,33): error CS0115: 'ObservableListEditor.AfterChange(SerializedProperty)': no suitable method found to override
```

**Comment by thestonefox** [comment]
You've probably not checked out the git submodule.

I've followed the set up guide many many times and it works every time.

**Comment by thestonefox** [comment]
You're also on a version of Unity that isn't supported

**Comment by dantman** [comment]
Submodules are checked out, Dependencies/Zinnia.Unity is there. I wouldn't have `ObservableListEditor.cs` in the first place if submodules were not checked out.

Sorry about the Unity version, I thought I was on the latest version. Unity/Unity Hub didn't let me know. I'll try updating.

**Comment by dantman** [comment]
Yup, it was the Unity version.
