### ISSUE TITLE
Assembly has reference to non-existent assembly 'Zinnia.Runtime' (Assets/VRTK-master/Prefabs/VRTK.Prefabs.Runtime.asmdef)

### ISSUE THREAD

**Issue by Jovonni** [ExtendRealityLtd/VRTK#1987]
### Environment

* Source of VRTK (Unity Asset Store or GitHub).
Github

* Version of VRTK (Unity Asset Store/GitHub release number) (GitHub master commit hash).
3.3.0

* Version of the Unity software (e.g. Unity 2018.3).
Unity 2018.3

* Hardware used (e.g. Vive/Oculus).
Oculus, but should't matter

### Steps to reproduce
Open unity 2018.3, and run the farm scene

### Expected behavior
Should play the Farm scene

### Current behavior
The following error appears:

"Assembly has reference to non-existent assembly 'Zinnia.Runtime' (Assets/VRTK-master/Prefabs/VRTK.Prefabs.Runtime.asmdef)"

### Additional
I began a new project, and dragged the entire cloned repo in the asset directory. From there, I open the scene and attempt to run "The Farm Scene" from within the project's directory structure

**Comment by guiguimanu** [comment]
How did you clone the repo? 

It sounds like you didn't download the dependencies. This will happen if you download the zip and unpack it. To fix this use a git clone command.

**Comment by bddckr** [comment]
As @guiguimanu said you have to follow the Readme. [Here](https://github.com/ExtendRealityLtd/VRTK#cloning-the-repo) is the section telling you how to.

As we're using this Issues page as a bug tracker/feature request/public roadmap tool I will close this issue and am asking you to move to our community: [Join us on Slack!](http://invite.vrtk.io)

**Comment by PratheepKP** [comment]
I tried git clone, but still, I'm getting the same error.

**Comment by bddckr** [comment]
@PratheepKP You'll have to *[follow the instructions](https://github.com/ExtendRealityLtd/VRTK#getting-started)*.

I believe you joined Slack and got a reply in <=2 minutes 🎉

**Comment by gregoraia** [comment]
I have the same problem here. @bddckr I can't find something about the git clone command you are saying above. Possibly the instructions have changed. Thanks for the help.

**Comment by thestonefox** [comment]
Try following the instructions

**Comment by bddckr** [comment]
Yeah just follow the linked instructions? Over the course of half a year things changed, don't read someone's comments in an issue here. Instead follow the _current_ readme :) Or you know, just ask for troubleshooting help on Slack :)
