### ISSUE TITLE
Must be touching interactable to perform ungrab

### ISSUE THREAD

**Issue by crashbandicool** [ExtendRealityLtd/VRTK#1988]
### Environment

* VRTK 4 master github commit 841eb0e
* Unity 2018.3.12f1 Win10
* SDK used : VRTK simulator

### Steps to reproduce

New scene with prefabs and modifications:
*Tracked alias 
*simulator 
*right hand interactor
     Grab rigged to button 1 of simulator rig
*Interactable.Primary_Grab.Secondary_None 
     Interactable.GrabReceiver: grab type: Toggle
     Interactable.GrabAction.FollowAction: Grab offset: Orientation Handle 
     **GenericOrientationHandle: transform x value = 1 (to move it outside the interactables collider).**

*Add empty game object to Interactable.Primary_Grab.Secondary_None with the following: 
     - unity button action with one source: Button 2 of simulator rig
    - following script which uses InteractorFacade.Ungrab and InteractableFacade.Ungrab 
   -  Drag RightHand Interactor reference into public field in inspector
   -   Under "Activated" in the unity button action, drag in the ManualUngrab script component  and select the DoUngrab method. 
------

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRTK.Prefabs.Interactions.Interactors;
using VRTK.Prefabs.Interactions.Interactables;

public class ManualUngrab : MonoBehaviour
{
	public InteractorFacade interactorRef;

	public void DoUngrab()
	{
		if (interactorRef.GrabbedObjects.Count > 0)
		{
			int count = 0; 
			Debug.Log("Interactor has stuff grabbed, attempting ungrab");
			
			foreach(GameObject element in interactorRef.GrabbedObjects)
			{
				element.GetComponent<InteractableFacade>().Ungrab(count);
				Debug.Log("count:" + count.ToString() + " name: " + element.name);
				count++;
			}
			
			interactorRef.Ungrab();
		}		
		
	}
}
```

------

### Expected behavior

Grab with mouse 1, ungrab with mouse 2 
The Interactor and or interactable expected to ungrab the object 

### Current behavior

The interactable remains in a grabbed state and cannot be dropped.

**Comment by thestonefox** [comment]
proposed fix
https://github.com/ExtendRealityLtd/VRTK/pull/1989
