### ISSUE TITLE
InteractorFacade.Ungrab .. then .. InteractorFacade.Grab(Instantiate(Prefab)) does not work

### ISSUE THREAD

**Issue by Mechandrius** [ExtendRealityLtd/VRTK#2003]
### Environment
Vrtk 4
unity 2019

### Steps to reproduce

I register an object touch. The object has a script with following code:

if(RightController touches object && RightTriggerPressed)
{
                GameObject go = Instantiate(Interactable.Grab.Prefab, transform.position, transform.rotation);
                InteractorFacadeRight.Ungrab();
                InteractorFacadeRight.Grab(go);
}

### Expected behavior

Drop current item, hold new instantiated item.

### Current behavior

First time: Grab instantiated item works but does not lose the grab when releasing the trigger
Further times: Still does not drop the first object. Holds multiple instantiated objects at same position in hand/controller

# Help

A howto/documentation for touch/grab control through scripts would be good

**Comment by thestonefox** [comment]
I don't understand the steps to reproduce.

You say you touch an object with the right trigger pressed then you expect it to drop a current item. but your steps don't show that you're holding an existing item.

**Comment by Mechandrius** [comment]
> I don't understand the steps to reproduce.
> 
> You say you touch an object with the right trigger pressed then you expect it to drop a current item. but your steps don't show that you're holding an existing item.
> 
> Could you please update with clear steps to reproduce the exact issue without skipping out any steps.

Hmm. Yes at the time of the first touch+trigger, there is no object held. Do you think that the code would function properly if I check for a held item before dropping? I would assume that Ungrab() does that check internally anways.

To make you understand the idea better of the functionality I try to achieve, I will illustrate further. I want to reach into a "zone" (touchable with special script) that when I grab (with trigger) does not grab the zone, but an other new instantiated object (grabable-prefab), that is then held like it was picked up normally.

Could you elaborate how you would solve this "instantiate + grab" functionality in code?

**Comment by thestonefox** [comment]
Slack is the place to ask for solutions to problems. GitHub is the place to raise bugs. If you think you've found a bug then provide clear steps to reproduce it. At the moment I am not understanding what the bug would be.
