### ISSUE TITLE
DestinationLocationConfigurator.cs EmitHoverDeactivated() emits HoverActivated 

### ISSUE THREAD

**Issue by NilsBernatzki** [ExtendRealityLtd/VRTK#2006]
### Pre-check

Your great naming conventions make this bug quite obvious.

### Environment

GitHub; VRTK v4 beta; 
master commit hash: d040e36ce05d63f97806984154635ff153c65d99

### Steps to reproduce

1. Call the DestinationLocationConfigurator EmitHoverDeativated() function.

2. The Facade's HoverActivated event fires, instead of its HoverDeactivated.

### Expected behavior

The EmitHoverDeactivated() function emits the HoverDeactivated event.

### Current behavior

The EmitHoverDeactivated() function invokes the HoverActivated event.

**Comment by thestonefox** [comment]
Good spot, I'll update it so it calls the correct behaviour

**Comment by thestonefox** [comment]
PR with fix: https://github.com/ExtendRealityLtd/VRTK/pull/2007
