### ISSUE TITLE
You can move your hands while climbing in VRTK Bug

### ISSUE THREAD

**Issue by D3V6N** [ExtendRealityLtd/VRTK#2009]
### Environment

VRTK from the asset store
V3
Unity V2018.3.6
Vive Headset
Steamvr SDK

### Steps to reproduce

Copy the example scene locomotion into my own scene, and delete all of the movement types except for climbing.

### Expected behavior

Climbing to work as normal, pretty self-explanatory.

### Current behavior
You can move your hands around while climbing, and your headset follows them, or at least I think that that is happening.

**Comment by thestonefox** [comment]
Does climbing work in the example scene?

If so, then this is not a bug but a configuration issue on your behalf and GitHub issues are only for raising bugs.

**Comment by D3V6N** [comment]
Climbing does not work in the example scene. I have tries with two different projects.

**Comment by thestonefox** [comment]
what do you mean you can move your hands around whilst climbing and your headset follows them?

If you move your hands whilst they're attached to something then you're moving your body, ergo moving the headset.

I've just tried in the example scene and it works fine for me.

![climbing](https://user-images.githubusercontent.com/1029673/57620706-7c690880-7581-11e9-8c44-51611a946fbc.gif)


If I were you, I'd check to make sure the SteamVR references haven't broken or anything in the example scene and if they have then delete them and re-add the relevant SteamVR prefabs in. For further help with that ask in the slack channel.

![image](https://user-images.githubusercontent.com/1029673/57620750-a0c4e500-7581-11e9-9c1c-1405729bc794.png)
