### ISSUE TITLE
Teleport Offset don´t work with Oculus Go

### ISSUE THREAD

**Issue by GoekhanOezcan-LivingBrain** [ExtendRealityLtd/VRTK#2013]
Environment
*Source of VRTK (GitHub).
*Version of VRTK (v4 Github master).
*Version of the Unity software (Unity 2019.1.1f1).
*Hardware used (Oculus Go).
*SDK used (UnityXR).

### Steps to reproduce

- Following the Documentation "Adding A Teleporter"
https://academy.vrtk.io/Documentation/HowToGuides/Locomotion/AddingATeleporter/

### Expected behavior

Teleport to the target place with the Camera Offset from the Oculus Go.

### Current behavior

The camera always lands at ground level.
It seems that the offset of Oculus Go Offset, is not passed.

I tried many Options:
Changed Target from PlayAreaAlias to different other Prefabs. Bad Idea.
If the Offset is "none" then the Camera is in the Right Position (Offset/Height).
I tried different other GameOjbects for the Offset, but it don´t work too.

**Comment by thestonefox** [comment]
Did you try the steps in this closed issue?

https://github.com/ExtendRealityLtd/VRTK/issues/1977

**Comment by GoekhanOezcan-LivingBrain** [comment]
Thank you :) the solution fixes the problem with the offset. Unfortunately, this now makes the controller movements very stiff. The controllers of course now firmly in their position and no longer make the swinging motion. But if you don´t change the Tracking Type from the LeftAnchor and RightAnchor, this problem is gone too.
