### ISSUE TITLE
Errors when download the VRTK 

### ISSUE THREAD

**Issue by atom182** [ExtendRealityLtd/VRTK#2016]
I am new in VRTK, when i donwload the project in my console apear 6 errors.

Assets\VRTK\Dependencies\Zinnia.Unity\Editor\Data\Collection\ObservableListEditor.cs(9,19): error CS0234: The type or namespace name 'FodyRunner' does not exist in the namespace 'Malimbe' (are you missing an assembly reference?)

Assets\VRTK\Dependencies\Zinnia.Unity\Editor\Data\Collection\ObservableListEditor.cs(17,41): error CS0246: The type or namespace name 'InspectorEditor' could not be found (are you missing a using directive or an assembly reference?)

Assets\VRTK\Dependencies\Zinnia.Unity\Editor\Data\Collection\ObservableListEditor.cs(160,33): error CS0115: 'ObservableListEditor.AfterChange(SerializedProperty)': no suitable method found to override

and others.

i don't know why happend this. i follow the steps included inthe documentation to clone the project. 

i hope somebody help me. thanks

**Comment by thestonefox** [comment]
Doesn't follow the issue template. Check your unity version
