### ISSUE TITLE
Teleporting through walls despite the ObscuranceQuery

### ISSUE THREAD

**Issue by DesperateHouseDev** [ExtendRealityLtd/VRTK#2022]
### Environment
VRTK v4 beta
master commit hash: 089b121 (May 24th)
Unity 2019.1
WMR Headset (Acer AH101)
Intel Core I7 2.8Ghz, 16GB Ram, Geforce GTX 1070

### Steps to reproduce
- Create a clean VRTK 4 project
- Play the example scene
- Try to reproduce this part of the VRTK V4 Beta Showcase (https://youtu.be/bBh10TYY-Xw?t=1755) where Theston E. Fox demonstrate how you can forbid teleporting through walls using ObscuranceQueries.
- Note that, in contrast to what is demonstrated in the video, you currently can teleport even when your controller goes through the wall

### Current behavior
The player can teleport through walls by putting his controller through them

### Expected behavior
He shouldn't be able to do so.

### Comment
After further testing, and trying to actually understand what's going on, I think that the `ObscuranceQueries` in the `VRTK Prefabs->AvatarPointers->PointerActions->PointersOccluded` children work fine: they are currently setup to enable/disable the `VRTK Prefabs->AvatarPointers->PointerActions->PointersPointerTeleportOnSelect->left (or right) SelectTeleport` game objects.
This work fine: these gameobjects are indeed enabled/disabled, when the controllers are visible/obscurred.
However, the actual teleport still occurs, and I think this is because these left (and right) SelectTeleport gameobjects are actually re-enabled by the left and right CurvedPointers in `VRTK Prefabs->AvatarPointers->TeleportPointers`, in their `PointerFacade/Selected` events, right before the actual teleport occurs.
Am I correct ? 
If so, I can think of several quick fixes, such as simply enabling/disabling the pointers themselveves (i.e. the `VRTK Prefabs->AvatarPointers->TeleportPointers` children gameobjects) depending on the `ObscurenceQueries` result, but please tell if you can think of a better fix, and/or if you plan to fix it yourselves in a future version.

**Comment by thestonefox** [comment]
The best solution is to just nest the TeleportSelect gameobjects in a container gameobject that the obscurancequery toggles on and off.

I'll update the example scene with this solution.

**Comment by DesperateHouseDev** [comment]
I've tested the fix that you did and merged today (Merge pull request #2025 commit hash 12df6d9 , June 3rd) and it works fine !
As far as I'm concerned this issue can now be closed (Shall I do it ?)
Thanks a lot for your work !
