### ISSUE TITLE
VRTK Default Input Mappings Prompt not showing in Unity 2019.1.4f1

### ISSUE THREAD

**Issue by ROBYER1** [ExtendRealityLtd/VRTK#2023]
### Environment

VRTK v4 beta
master commit hash: 089b121 (May 24th)
Unity 2019.1.4f1
WMR Headset (Lenovo Explorer)
Intel Core I7 2.21 Ghz, 16GB Ram, Nvidia RTX 2070

### Steps to reproduce

Following the readme of the VRTK git exactly - make a new 3d project, set the appropriate .NET version, install XR bindings package and enable Virtual Reality support.

Clone the VRTK repo into the Assets folder
Open the unity project (or keep it open while cloning)
See that the input mappings warning doesn't show once everything has imported.

### Expected behavior

VRTK input mappings window should pop up

### Current behavior

 input mappings warning doesn't show once everything has imported.

**Comment by thestonefox** [comment]
I just tried in 2018.4.1f1 and it worked fine. I'll try in 2019.1.4f1 and see if I can recreate.

**Comment by thestonefox** [comment]
I just tried in 2019.1.4f1 in a fresh project and it worked fine for me.

If someone else can confirm, then I can close this ticket.
