### ISSUE TITLE
Seated with Free-Move locomotion causes BodyRepresentation to get stuck in ground

### ISSUE THREAD

**Issue by ROBYER1** [ExtendRealityLtd/VRTK#2035]
### Environment

* Github
* VRTK v4 commit 6e769d48
* Unity 2019.1.6f1
* Lenovo Explorer WMR Headset
* OpenVR

### Steps to reproduce

1. Create a terrain with a few slight inclines
2. Set up the VRTKElements for a character controller (do this by opening the farm, ctrl-c the VRTK parent objects for the player and locomotion swatch menu popup and ctrl-v them into the new scene with terrain)
3. Hit play WHILE SEATED
4. Open the locomotion options menu and switch to the free axis movement (all the way left)
5. Walk towards a small incline and see that the player gets stuck, try running all over the terrain with various levels of bumps - I am happy to provide an example
6. This may be possible to recreate if the player starts to crouch while moving forward with the axis

### Expected behavior

Player should free move smoothly over terrain even while seated

### Current behavior

Being seated pushed the collider(?) into the floor even though it appears to be fine in the editor view and movement completely stops until the player is lifted off the ground on the Y axis and dropped onto the ground to continue moving freely.

**Comment by thestonefox** [comment]
I cant recreate this.

![image](https://user-images.githubusercontent.com/1029673/59967960-27c68f00-952a-11e9-8b93-de3757a9948e.png)

That's my test and I can traverse the terrain just fine whilst seated.

**Comment by ROBYER1** [comment]
I have produced an example of this (video included) so you can see what I am experiencing, notice in the video I take the assets exactly as is from the example scene to avoid any errors

https://drive.google.com/file/d/17aTLwgves1YOR9zvp2ZU48SP49UNADs2/view?usp=sharing
