### ISSUE TITLE
Teleport snap to floor incorrect 

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/VRTK#2042]
### Environment

* Source of VRTK (GitHub).
* Version of VRTK (61c746b73b87730bc898aa754e21b2e8f8cf00a3).
* Version of the Unity software (e.g. Unity 2019.1.0f2).
* Hardware used (e.g. Vive).
* SDK used (OpenVR).

### Steps to reproduce

1. Open ExampleScene
2. Touch Trackpad to activate teleport pointer
3. Point to HouseFrontVeranda and/or HouseFoundation
4. Press Trackpad to teleport

### Expected behavior

The pointer correctly identify that the location is above ground level (on the veranda/foundation).
The teleported location is above ground level (on the veranda/foundation).

### Current behavior

The pointer correctly identify that the location is above ground level (on the veranda/foundation).
BUT the teleported location is at ground level.

**Comment by thestonefox** [comment]
I dont think this is a problem with the snap to floor, i think it's a problem with how the model for the farm house is such a massive scale and the colliders are massively scaled down so unity isn't handling the ray collision all that well.

The solution would be to better scale the farm house i think so it doesnt need such extreme numbers

**Comment by fight4dream** [comment]
I have a destination location variant, it has a pillar about 1.8x3.2x1.8 meter, a visual "aura" pivot at the top of pillar. The LocationDestinationOverride is at the top of pillar. The CasterPointOverride is 0.5 above the pillar. The pillar has a convex mesh collider.

Most of the time, it will teleport me correctly standing on top of pillar.
Sometimes it will teleport me below and slightly off the back of the pillar.
The y-coord of the mis-teleported player is always -6. I wonder what is the implication of this. I have very large floor collider at zero, but none collider is at -6.

I have tried to raise the LocationDestinationOverride and CasterPointOverride a bit to avoid clipping into own pillar but the symptom persists.

**Comment by mattdavisgames** [comment]
Hi, I've run into this same bug in my own scenes. After digging through the code, I've fairly sure I've found the issue.

In `SurfaceLocator.FindAllCollisions()`, after calling `ArraySortExtensions<RaycastHit>.Sort(raycastHits.Array, raycastHits.Offset, raycastHits.Count, Comparer, Comparison);`, the raycast results are sometimes sorted incorrectly. I haven't narrowed the bug down any further, but it happens consistently on the same objects and in each case I've seen so far, the unsorted array is in the same order as the "sorted" array.

**Comment by fight4dream** [comment]
Thanks @mattdavisgames . I dig further into the 'Comparer' used.
It is `SurfaceLocator.RayCastHitComparer` and its compare function is `return (int)(x.distance - y.distance);`
I think this is incorrect and will should be `return x.distance.CompareTo(y.distance)`
