### ISSUE TITLE
Outline shader on Oculus Quest

### ISSUE THREAD

**Issue by yannoid** [ExtendRealityLtd/VRTK#2043]
### Environment

* VRTK4 beta - GitHub.
* commit 61c746b73b87730bc898aa754e21b2e8f8cf00a3
* Unity 2019.1.8f1
* Oculus Quest.
* Oculus Integration / SALSA / Easy combine / Playmaker.

### Steps to reproduce

> Open the farm scene, build on Oculus (with academy's lessons on Oculus avatar and velocity integration)

> Gaze at an outlined object, like the tools

### Expected behavior

> A yellow outline shoud be seen

### Current behavior

> The screen turns black as soon as the yellow instancied material loads the outline shader
> Even force close my app on a custom scene

![settings](https://user-images.githubusercontent.com/7513914/61272081-89cf8880-a7a6-11e9-9357-34b67940756e.jpg)
![2](https://user-images.githubusercontent.com/7513914/61272082-89cf8880-a7a6-11e9-93bf-e15a9bf3d00c.png)
![1](https://user-images.githubusercontent.com/7513914/61272083-89cf8880-a7a6-11e9-8d7b-26e67c25f08a.png)

**Comment by DirtyOleg** [comment]
I had similar problem with Oculus Go using unity 2018.3.11f. When you assign an outline shader to a cube, it will turn that cube to black and only highlight the 8 corner of that cube.

**Comment by SiriusA7** [comment]
Had this issue with my quest as well.
@DirtyOleg did you end up finding a solution?

**Comment by DirtyOleg** [comment]
@SiriusA7 Have not looked into the problem yet. My guess is that the VRTK outline shader is not optimized for Android device. However, I may be wrong, since I have limited knowledge about shader.

**Comment by thehen** [comment]
Having the same issue here

**Comment by DirtyOleg** [comment]
I do not know how, but when I remove VRTK from my project and reimport it, the outline is working fine again.

**Comment by Corysia** [comment]
Oculus recommends mobile to use linear, too.  [Unity Settings for Mobile VR](https://developer.oculus.com/blog/tech-note-unity-settings-for-mobile-vr/)

**Comment by thestonefox** [comment]
The farm example is just a basic example shader. I'd recommend using better outline shaders from the Unity Asset Store
