### ISSUE TITLE
Controllers are not showing up in any of the examples SOLVED

### ISSUE THREAD

**Issue by jackbashed** [ExtendRealityLtd/VRTK#2052]
Got it to work nvm

**Comment by bddckr** [comment]
Please head to [![Slack][Slack-Badge]][Slack] for troubleshooting help next time. GitHub issues should follow the template and are for bug reports primarily.

**Comment by bruno1308** [comment]
What was the issue? I can't seem to make my TrackedAlias work after upgrading my VRTK to the latest version.

**Comment by bddckr** [comment]
With the project changing all the time you're better off creating a new issue (and following the issue template). Don't be shy creating new issues. Replying to old ones doesn't give it any visibility!

I believe you're getting help in Slack already though.
