### ISSUE TITLE
Shotgun pump issue

### ISSUE THREAD

**Issue by DesperateHouseDev** [ExtendRealityLtd/VRTK#2060]
### Environment
VRTK v4 beta
master commit hash: 1c6ba2a (September 25th)
**Unity 2019.3.0b4**
WMR Headset (Acer AH101)
Intel Core I7 2.8Ghz, 16GB Ram, Geforce GTX 1070

### Steps to reproduce
- Create a clean VRTK 4 project
- Play the example scene (in the editor on in a standalone build)
- Grab (or distance grab) the shotgun with one hand
- Grab (**but not distance grab**) and hold the shotgun pump with the other hand
- Note that you are unable to move the pump
- Release the pump and distance-grab it instead
- Note you are now able to move the pump

### Current behavior
The shotgun pump won't move if it is grabbed (and not distance-grabbed)

### Expected behavior
Being able to move the pump while using simple grabs

### Comment
Hello guys, I started a new VRTK 4 project yesterday and noticed the above issue.
Please note that : 
- This is no big deal and I should be able to correct it myself. But in case other people are concerned, I thought it would be a good idea to raise the issue
- Maybe this is the expected behavior, or a known, too-tricky-to-solve issue. In such case, please feel free to close it
- This is the first time I notice that issue, although I've already done some tests on VRTK4 a few months ago (in May) without noticing it. I've reopened these old tests and it seems the issue was already there, but :
- The issue happens in Unity 2019.3.0 beta which I'm trying for the first time, and this is the only notable thing that recently changed in my setup. There is a chance it did not happen with older unity versions. I've removed older versions from my PC but please tell me if you want me to reinstall them and check

Please feel free to ask if you need any additional infos, video capture, tests, or so.

Thanks in advance !

**Comment by thestonefox** [comment]
does it happen in 2019.2?

we don't support Unity beta software as things can and do change a lot with Unity betas

**Comment by DesperateHouseDev** [comment]
I will reinstall it and check. I'll be back in a while

**Comment by DesperateHouseDev** [comment]
Indeed I can't reproduce the issue in Unity 2019.2.
Please feel free to close the issue then (hoping it won't pop again once Unity 2019.3 is released :) )
