### ISSUE TITLE
Make compatible with the Unity Package Manager and remove git submodule

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK#2065]
Currently VRTK imports Zinnia into the project via a git submodule, which in turn includes the hard dependency of Malimbe.

There is some work to be done on Zinnia to make it a valid Unity package and remove the hard dependency of Malimbe.

When this happens it will break VRTK as there is a requirement to pull in the dependencies via a git submodule.

Moving forward, including VRTK will require including the package in the project manifest.

Zinnia ticket reference https://github.com/ExtendRealityLtd/Zinnia.Unity/issues/430

**Comment by thestonefox** [comment]
As each Prefab will be split out into its own repo eventually, I wonder if the easiest way forward right now is to just nest the Prefabs directory within a Runtime directory.

```
Runtime/
--Prefabs/
```

Then there only has to be 1 asmdef under runtime right now. In the future each repo will contain its own Runtime and asmdef.

**Comment by bddckr** [comment]
![Unity_2019-10-14_23-20-38](https://user-images.githubusercontent.com/294347/66784162-f8bd9a00-eed9-11e9-8592-769c0fcd1208.png)
🎉

For anyone wondering: Instructions on how to consume can be found in the README, as always!
