### ISSUE TITLE
VRTK4 not compiling after download/clone from git

### ISSUE THREAD

**Issue by Flekoun** [ExtendRealityLtd/VRTK#2070]
Hi, the VRTK4 plugin simply does not compile properly when downloaded to project. I have followed all instructions ( XR settings, player Settings atc) I have tried to download zip or get from github via bash.
I think that issues is that Zinnia is not fetched with the VRTK? 
I get a 94 errors whcih looks like this:
"The type or namespace name 'Zinnia' could not be found"
"The type or namespace name 'Malimbe' could not be found"
etc..

Source of VRTK : GitHub
Version of VRTK : master GitHub
Version of unity : 2019.2.9f1
Hardware : Oculus

**Comment by thestonefox** [comment]
The vrtk repository is a unity project, you can't put a unity project inside another unity project. Follow the instructions on the readme. 

If you just want the vrtk prefabs in your project then use this repository https://github.com/ExtendRealityLtd/VRTK.Prefabs

And be sure to read the instructions.
