### ISSUE TITLE
Origin of slider moving when root object is scaled

### ISSUE THREAD

**Issue by vicou96** [ExtendRealityLtd/VRTK#2074]
### Environment

* Code source: Asset store unity VRTK
* Code version: 3.3.0
* Platform version: 2019.2.11f1
* 3rd party dependencies: none

### Steps to reproduce

1) Go to scene example 005 - Interactions
2) Scale the FreeSlidePhysicsSlider to 0.9 0.9 0.9

### Expected behavior

 The SliderControl object stay at the position of the SliderContainer when the scene is played

### Current behavior

The SliderControl object is moved toward the position when it was scaled to 1 1 1 (in the example the object is going backward) when playing the scene

**Comment by thestonefox** [comment]
VRTK v3 is no longer being developed. If you have an issue then best bet is to ask in the slack channel at  http://invite.vrtk.io
