### ISSUE TITLE
Oculus Quest TriggerHapticPulse pretty weak vibrating

### ISSUE THREAD

**Issue by Markovicho** [ExtendRealityLtd/VRTK#2088]
### Environment

* Code source:  VRTK Github Repo
* Code version: 3.3.0
* Scene: 016_Controller_HapticRumble
* Platform version: Unity 2018.4.14 
* 3rd party dependencies: Oculus Integration SDK (Asset Store Version)

### Steps to reproduce

Installed Oculus Integration for Unity from Asset Store
Integrated OVRCameraRig as SDK Setup to connect with VRTK_SDK Manager
SDK-Selection GearVR (Android Oculus)
Status Quo: Fully working Interactions with the Quest-Controllers

Testscene: 016_Controller_HapticRumble 

### Expected behavior

Haptic Feedback (Rumble) using should be behaving like in other Oculus Quest Apps (strong rumble).

### Current behavior

Haptic Feedback is basically triggered but is prett weak. I changed the call in Sword.cs from

VRTK_ControllerHaptics.TriggerHapticPulse(controllerReference, hapticStrength, 0.5f, 0.01f);
to
VRTK_ControllerHaptics.TriggerHapticPulse(controllerReference, 1.0f, 0.5f, 0.01f);

to ensure using the maxstrength value in VRTK_ControllerHaptics. But the controller vibrations are still almost not noticable. 

thanks in advance for any kind of support in this case :-)

**Comment by thestonefox** [comment]
v3.3 is no longer supported. Best to ask in the VRTK slack channel http://invite.vrtk.io
