### ISSUE TITLE
ClickAfterHoverDuration takes 2x time than declared

### ISSUE THREAD

**Issue by aleksanderwlodarczyk** [ExtendRealityLtd/VRTK#2092]
### Environment

* Code source: Github
* Code version: Github `bf58445`
* Platform version: Unity 2019.2.3

### Steps to reproduce

Create Unity buttons on VRTK_UICanvas and set VRTK_UIPointer to click on hover after time f.e 10 seconds.

### Expected behavior

After looking on button it should invoke button's onClick actions after 10 seconds.

### Current behavior

After looking on button it invokes button's onClick actions after about 20 seconds.

**Comment by thestonefox** [comment]
VRTK v3 is no longer supported and bugs will not be fixed in this version.
