### ISSUE TITLE
Does it support PSVR?

### ISSUE THREAD

**Issue by dpggit** [ExtendRealityLtd/VRTK#2095]
I would like to know if psvr works with vrtk or if there are plans for it atm

**Comment by Otterrat** [comment]
A community member added rudimentary support for PSVR in VRTK:

https://connect.unity.com/p/psvr-for-vrtk

You will still need access to the PSVR SDK (As in, have a Sony Developer account)to enable device tracking.

**Comment by thestonefox** [comment]
V3 has community support on the PSVR forum, V4 _should_ *just work*
