### ISSUE TITLE
VRTK Input mapping tool

### ISSUE THREAD

**Issue by L4Z3RC47** [ExtendRealityLtd/VRTK#2098]
It looks like the input mapping tool (as mentioned in the now out of date https://www.youtube.com/watch?v=uZ1VBWSlOnc) is no longer included as a part of the repo? Would love to have this back ;)

**Comment by thestonefox** [comment]
It is back in the Tilia unity input manager repo
https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputManager

The VRTK.Prefabs is slowly being retired in place of the independent Tilia repos.
