### ISSUE TITLE
Super Simple: Please Change the Positive Bounds On FloatToBoolean to public not protected

### ISSUE THREAD

**Issue by Par3val** [ExtendRealityLtd/VRTK#2103]
## Is your feature request related to a problem?

Kind of, it certainly gets in the way of any automation or consolidation

I'm always frustrated when I want to check the PositiveBounds of a FloatToBoolean and there is no way to read the min/max

## Describe the solution you'd like

change L:33 of FloatToBoolean.cs for

protected FloatRange PositiveBounds { get; set; } = new FloatRange(0f, 1f);

to

public FloatRange PositiveBounds { get; set; } = new FloatRange(0f, 1f);

## Describe alternatives you've considered

or add a GetPositiveBounds() to match the SetPositiveBounds

**Comment by bddckr** [comment]
Making the setter public means it needs way more than the suggested change as the change of the property has to be reacted to at runtime.

An alternative would be
```c#
public FloatRange PositiveBounds { get; protected set; } = new FloatRange(0f, 1f);
```

I can't remember if Malimbe's serialized properties support that, though.

**Comment by thestonefox** [comment]
https://github.com/ExtendRealityLtd/Zinnia.Unity/blob/dcead0dd8afa99cc044ed9b7d35aba9dfa617037/Runtime/Data/Type/Transformation/Conversion/FloatToBoolean.cs#L30
