### ISSUE TITLE
How to rotate the player in 45 degree steps?

### ISSUE THREAD

**Issue by rabejens** [ExtendRealityLtd/VRTK#2105]
I followed the howtos at [academy.vrtk.io](https://academy.vrtk.io/) and set up a basic scene where I can teleport around and grab an object. Now, I want to implement player rotating, i.e., when I push the right thumbstick left or right, I want to rotate in 45-degree steps.

I could not figure out how to do it. I tried setting up an `AxisRotator` with the target set to my `PlayAreaAlias` and the Direction Offset set to `HeadsetAlias`, and for the lateral axis, I set a `FloatAction` which is attached to an empty `GameObject`. The code for the `FloatAction` is the following:

```csharp
using System;
using UnityEngine;
using Zinnia.Action;

public class RotationAction : FloatAction {

    public string AxisName;
    private sbyte _currentRotationDirection;
    private float _angle;

    // Update is called once per frame
    protected virtual void Update() {
        var axisValue = Input.GetAxis(AxisName);
        if(axisValue < -0.75f && _currentRotationDirection != -1) {
            _angle -= 45f;
            _currentRotationDirection = -1;
        } else if(axisValue > 0.75f && _currentRotationDirection != 1) {
            _angle += 45f;
            _currentRotationDirection = 1;
        } else if(axisValue >= -0.75f && axisValue <= 0.75f && _currentRotationDirection != 0) {
            _currentRotationDirection = 0;
        }
        Receive(_angle / 180f * (float)Math.PI);
    }
}
```

I set the `AxisName` to `VRTK_Axis4_RightHorizontal` which, as I discovered, maps to the right thumbstick. When I push the stick left or right, I do get a rotation, but not by 45 degrees, but by an arbitrary angle. Using the degrees directly and not converting them to radians does not help either.

Am I on the right track or has this done differently? Can anyone point that out?

I am using VRTK v4 Beta with Unity 2019.3.0f6 and Oculus Quest.

**Comment by FireDragonGameStudio** [comment]
There is actually a snap turn tutorial on the Unity Learn platform. It's a little bit hidden, but worked for me 🙂 Check out Unit 4, Chapter 11 of the Design, Develop, and Deploy for VR tutorial -> [https://learn.unity.com/tutorial/unit-4-locomotion-and-ergonomics](https://learn.unity.com/tutorial/unit-4-locomotion-and-ergonomics)

Best regards :)

**Comment by thestonefox** [comment]
https://github.com/ExtendRealityLtd/Tilia.Locomotors.AxisMove.Unity/tree/master/Documentation/HowToGuides/AddingSlideMovementWithSnapRotation
