### ISSUE TITLE
Unity2019.3.4f1Can't load the manifest.json for VRTK4

### ISSUE THREAD

**Issue by iqxtreme** [ExtendRealityLtd/VRTK#2107]
VRTK4: You can't open this project with Unity2019.3.4f1
![2020-04-11 221851](https://user-images.githubusercontent.com/3447410/79061039-7c581800-7cbe-11ea-959c-af51f75edf39.png)

**Comment by thestonefox** [comment]
I would double check you've added the scopedRegistry to the manifest.json correctly.

This isn't a bug in VRTK, if you need further help with this then visit the slack channel at http://invite.vrtk.io and see if someone in there can help you.

**Comment by iqxtreme** [comment]
> I would double check you've added the scopedRegistry to the manifest.json correctly.
> 
> This isn't a bug in VRTK, if you need further help with this then visit the slack channel at http://invite.vrtk.io and see if someone in there can help you.

thanks!
