### ISSUE TITLE
Trinus integration for a rapid tests

### ISSUE THREAD

**Issue by studentutu** [ExtendRealityLtd/VRTK#2111]
## Is your feature request related to a problem?
It is a great pleasure to test the project even without the headset, but still, at some point it needs to be done. 

## Describe the solution you'd like
There is a ready solution for such a thing - https://www.trinusvirtualreality.com/ - it works by translating the video data from your pc into the device app via USB(Android) or Wifi (IOS/Android) with the addition of getting the positional data back into the player as mouse movement,

## Describe alternatives you've considered
The only thing that is missing in VRTK is an additional guide on how to test the complete game with the trinus

## Additional context
![image](https://user-images.githubusercontent.com/18601652/85864214-e2880d80-b7cc-11ea-9de4-225f90b665f7.png)

**Comment by thestonefox** [comment]
This is nothing to do with VRTK
