### ISSUE TITLE
CameraColorOverlay Black OnEnable

### ISSUE THREAD

**Issue by podgypig120** [ExtendRealityLtd/VRTK#2112]
### Environment

* Source of VRTK (Unity Asset Store or GitHub).

VRTK Tilia Repo

* Version of VRTK (Unity Asset Store/GitHub release number) (GitHub master commit hash). 
VR - Tilia

* Version of the Unity software (e.g. Unity 2018.3.10f1). 

2020.1b

* Hardware used (e.g. Vive/Oculus).

Oculus Rift S

* SDK used (e.g. OpenVR/SteamVR/Oculus Utilities).

Oculus Utilities/Integration

### Steps to reproduce

When in Runtime, switching on any of the new movement prefabs in Tilia which call their own CameraColorOverlay causes the cameraColorOverlay to generate a new material which takes over the camera, making it black. This is an issue as I have a menu for the player to switch between Snap or Smooth rotate and Teleport or Vertical-smooth move.

The Teleporter and SnapRoate have their own CameraColourOverlay "Blink" children which causes this issue whenever they are enabled in the scene.

### Expected behavior

When enabling SnapRotate or Teleporters Prefab or Vertical Blink (or any Tilia package with a Blink child), there is no affect on the camera view.

### Current behavior

Tilia prefab for each movement is enabled, the camera goes fully black as the OnEnable generates a new material which overtakes the camera image. In default, this makes the camera go fully black with a new black material. A bool in the CameraColorOverlay inspector saying "generate new material on enable?" or similar would probably fix this problem.

**Comment by thestonefox** [comment]
I can't recreate.

I added a teleporter and the SnapRotate axis move to a scene, disabled the SnapRotate gameobject

started the scene then turned off the teleporter and then turned on the SnapRotate gameobject

I saw no fade.

**Comment by podgypig120** [comment]
Strange! It happens consistently for me, its 100% the OnEnable create new material. Anyway, you can ignore it and I can just extend the base scripts and overwrite if I need to I suppose

**Comment by thestonefox** [comment]
you need to provide clear steps to reproduce it
