### ISSUE TITLE
Unable to edit SnapZoneHighlight

### ISSUE THREAD

**Issue by vika2011** [ExtendRealityLtd/VRTK#2115]
### Environment

* Source of VRTK: GitHub
* Version of VRTK: GitHub v4
* Version of the Unity software:  Unity 2018.3.10f1.
* Hardware used:  none.
* SDK used:  SteamVR.

### Steps to reproduce
By adding an "InteractableSnapZone" prefab into the scene, I can't edit anything of the "SnapZoneHighlight" component in its inspector.

### Expected behavior

To change the shader of the SnapZoneHighlight.

### Current behavior

Can not edit anything of the SnapZoneHighlight.
![vrtk1](https://user-images.githubusercontent.com/53818558/113825021-0f813c00-97b3-11eb-9182-788667897c57.png)

**Comment by thestonefox** [comment]
You haven't provided the steps of what you're trying to change so it's not possible to recreate this issue. In fact your screenshot shows you've changed the elements within the highlight mesh.

Also, it looks like you're on an old version if the shader is called `VTRK/Outline_color` as it has been called `Tilia/Outline_color` for quite a while now

**Comment by vika2011** [comment]
> You haven't provided the steps of what you're trying to change so it's not possible to recreate this issue. In fact your screenshot shows you've changed the elements within the highlight mesh.
> 
> Also, it looks like you're on an old version if the shader is called `VTRK/Outline_color` as it has been called `Tilia/Outline_color` for quite a while now

Well I think is the problem with the default material and I can fix it by replacing its material. Thx for your help.
