### ISSUE TITLE
Please provide update instructions to Unity 2020 on mainpage

### ISSUE THREAD

**Issue by primepeter** [ExtendRealityLtd/VRTK#2128]
**Unity Version**: 2020.3
**VRTK Version** (downloaded through Asset Store ): 3.3.0

I've found nowhere a clear statement, that VRTK 3.3.0 isn't compatible with Unity 2020. 
But when downloading in Asset Store, the examples doesnt compile.
The only compatibility statement i've found everywhere is "supports Unity version 5.6.5 or higher".

Finally, I've found a tutorial on how to convert VRTK 3.3.0 to be Unity 2020 compatible here:
VRTK.Tutorials.VRBowling/Documentation/Tutorials/03.ConvertingToUnity2020/

I guess for newbies it would be of great benefit, if it would be statet more visible that VRTK needs conversion effort to be compatible with Unity 2020.
And the steps to replace the old legacy Unity XR System wit the new XR Plug-in Framework could be a seperate tutorial, easy findable when searchign for VRTK and Unity 2020.

**Comment by thestonefox** [comment]
VRTK v3.3.0 has been deprecated and is no longer supported.

The tutorial you mention is for VRTK v4 and not VRTK v3.3.0

There is no way on the Unity Asset Store where you can put in a max version, only a min version
