### ISSUE TITLE
errors when i selected selected sdk_oculus_avatar

### ISSUE THREAD

**Issue by ShiYuchun97** [ExtendRealityLtd/VRTK#2130]
unity:2019.1.3
vrtk:3.3
sdk: oculus integration
when I selected sdk_oculus_avatar, it showed 
"Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs(692,32): error CS1061: 'OvrAvatar' does not contain a definition for 'AssetsDoneLoading' and no accessible extension method 'AssetsDoneLoading' accepting a first argument of type 'OvrAvatar' could be found (are you missing a using directive or an assembly reference?)"
can anyone help!!!

**Comment by thestonefox** [comment]
VRTK 3.3. is no longer supported.

You can try and ask the community for help in the discord channel at http://chat.vrtk.io/
