### ISSUE TITLE
Error with Unity 2021.2.2f

### ISSUE THREAD

**Issue by kndol** [ExtendRealityLtd/VRTK#2131]
Error with Unity 2021.2.2f:

Mesh.uv4 is out of bounds. The supplied array needs to be the same size as the Mesh.vertices array.
UnityEngine.Mesh:SetUVs (int,System.Collections.Generic.List`1<UnityEngine.Vector3>)
Outline:LoadSmoothNormals () (at Assets/ThirdParty/QuickOutline/QuickOutline/Scripts/Outline.cs:195)
Outline:Awake () (at Assets/ThirdParty/QuickOutline/QuickOutline/Scripts/Outline.cs:96)

**Comment by thestonefox** [comment]
this isn't a bug report, it's just an error message
